version: '3.7'
services:
  jenkins-slave-slave1-1-production:
    command: java -jar /usr/share/jenkins/slave.jar -jnlpUrl http://192.168.0.29/computer/slave1-1/slave-agent.jnlp -workDir "/home/jenkins"
    container_name: jenkins-slave-slave1-1-production
    image: synapticon/somanet-jenkins-slave:3.27-1-alpine
    devices:
      - /dev/EtherCAT0:/dev/EtherCAT0
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    privileged: true
    restart: always
    volumes:
      - jenkins-data:/home/jenkins
      - /dev:/dev
      - /opt/etherlab/bin/ethercat:/opt/etherlab/bin/ethercat
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-slave-slave1-1-development:
    command: java -jar /usr/share/jenkins/slave.jar -jnlpUrl http://192.168.0.29:1234/computer/slave1-1/slave-agent.jnlp -workDir "/home/jenkins"
    container_name: jenkins-slave-slave1-1-development
    image: synapticon/somanet-jenkins-slave:3.27-1-alpine
    devices:
      - /dev/EtherCAT0:/dev/EtherCAT0
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    privileged: true
    restart: always
    volumes:
      - jenkins-data-development:/home/jenkins
      - /dev:/dev
      - /opt/etherlab/bin/ethercat:/opt/etherlab/bin/ethercat
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
  jenkins-data-development:

